title: Baek Cheol Kim blog
description: mostly til
theme: just-the-docs

url: https://baekcheolkim.github.io/

repository: BaekCheolKim/BaekCheolKim # for github-metadata

#aux_links:
#Template Repository: https://github.com/just-the-docs/just-the-docs-template
